### ISSUE TITLE
Environment variables are lost when running sbt fork

### ISSUE THREAD

**Issue by omj** [kamon-io/sbt-kanela-runner#3]
Due to https://github.com/kamon-io/sbt-kanela-runner/blob/bacc1ea20d427c2a1b498639d3d547139e66a9eb/sbt-kanela-runner/src/main/scala/kamon/instrumentation/sbt/SbtKanelaRunner.scala#L78 environment variables specified in build.sbt 

```
envVars in run ++= Map( 
...
)
```

are lost

**Comment by ivantopo** [comment]
Hey @omj, thanks for bringing this up. It was just fixed and released as 2.0.4 :smile:

**Comment by cosmir17** [comment]
Thank you, @ivantopo I really appreciate your professional kindness.
